apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: team-cool-kids-runtime
  destination:
    namespace: team-cool-kids-runtime
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: 'https://github.com/martinl373/team1-argo-monotest.git'
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
